//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionPozosPemex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Campo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campo()
        {
            this.Operacions = new HashSet<Operacion>();
            this.Pozoes = new HashSet<Pozo>();
            this.Precios = new HashSet<Precio>();
            this.Resultadoes = new HashSet<Resultado>();
        }

        public int CampoId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo Nombre es requerido.")]
        public string Nombre { get; set; }
        [Required]
        public int ActivoId { get; set; }
        [Required]
        public int RegionId { get; set; }
        [DisplayName("Factor de Declinación")]
        [Range(0, 9999), Required(AllowEmptyStrings = false, ErrorMessage = "El campo Factor de Declinación es requerido.")]
        public double Declinacion { get; set; }
        [DisplayName("Gasto Fijo")]
        [Range(0, 9999), Required(AllowEmptyStrings = false, ErrorMessage = "El campo Gasto Fijo es requerido.")]
        public double GastoFijo { get; set; }
        [DisplayName("Gasto Variable")]
        [Range(0, 9999), Required(AllowEmptyStrings = false, ErrorMessage = "El campo Gasto Variable es requerido.")]
        public double GastoVariable { get; set; }
        [DisplayName("Gasto Total")]
        [Range(0, 9999), Required(AllowEmptyStrings = false, ErrorMessage = "El campo Gasto Total es requerido.")]
        public double GastoTotal { get; set; }
        [DisplayName("Factor de Conversión Gas-Crudo")]
        [Range(0, 9999), Required(AllowEmptyStrings = false, ErrorMessage = "El campo Factor de Gas a Crudo es requerido.")]
        public double GasCrudo { get; set; }

        public virtual Activo Activo { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacion> Operacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pozo> Pozoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultado> Resultadoes { get; set; }
    }
}
