//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionPozosPemex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Operacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operacion()
        {
            this.Resultadoes = new HashSet<Resultado>();
        }
    
        public int OperacionId { get; set; }
        public int CampoId { get; set; }
        public int EquipoId { get; set; }
        public int PozoId { get; set; }
        [DisplayName("OPEX")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo OPEX es requerido.")]
        public double Opex { get; set; }
        [DisplayName("Factor de Conversión Gas-Aceite")]
        [Range(0,999999),Required(AllowEmptyStrings = false, ErrorMessage = "El campo Factor de Conversión Gas-Aceite es requerido.")]
        public double GasAceite { get; set; }
        [DisplayName("RGA")]
        [Range(0,999999),Required(AllowEmptyStrings = false, ErrorMessage = "El campo RGA es requerido.")]
        public double Rga { get; set; }
        [DisplayName("Tasa Impositiva")]
        [Range(0,999999),Required(AllowEmptyStrings = false, ErrorMessage = "El campo Tasa Impositiva es requerido.")]
        public double tasaImpositiva { get; set; }
        [DisplayName("Paridad Cambiaria")]
        [Range(0,999999),Required(AllowEmptyStrings = false, ErrorMessage = "El campo Paridad Cambiaria es requerido.")]
        public double Paridad { get; set; }
    
        public virtual Campo Campo { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Pozo Pozo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultado> Resultadoes { get; set; }
    }
}
