//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionPozosPemex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Pozo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pozo()
        {
            this.Operacions = new HashSet<Operacion>();
            this.Resultadoes = new HashSet<Resultado>();
        }

        public int PozoId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo Nombre es requerido.")]
        public string Nombre { get; set; }
        [DisplayName("Número de Barriles")]
        [Range(0,99999),Required(AllowEmptyStrings = false, ErrorMessage = "El campo Número de Barriles es requerido.")]
        public int Barriles { get; set; }
        [DisplayName("Número de Meses")]
        [Range(0,999999),Required(AllowEmptyStrings = false, ErrorMessage = "El campo Número de Meses es requerido.")]
        public int Meses { get; set; }
        [Required]
        public int CampoId { get; set; }

        public virtual Campo Campo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacion> Operacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultado> Resultadoes { get; set; }
    }
}
