//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionPozosPemex.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PozosPemexEntities : DbContext
    {
        public PozosPemexEntities()
            : base("name=PozosPemexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activo> Activoes { get; set; }
        public virtual DbSet<Campo> Campoes { get; set; }
        public virtual DbSet<Equipo> Equipoes { get; set; }
        public virtual DbSet<Operacion> Operacions { get; set; }
        public virtual DbSet<Pozo> Pozoes { get; set; }
        public virtual DbSet<Precio> Precios { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Resultado> Resultadoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int sp_calcularOpex(Nullable<double> gas_aceite, Nullable<double> rga, Nullable<double> tasaImpositiva, Nullable<double> paridad, Nullable<int> campo_id, Nullable<int> equipo_id, Nullable<int> pozo_id)
        {
            var gas_aceiteParameter = gas_aceite.HasValue ?
                new ObjectParameter("gas_aceite", gas_aceite) :
                new ObjectParameter("gas_aceite", typeof(double));
    
            var rgaParameter = rga.HasValue ?
                new ObjectParameter("rga", rga) :
                new ObjectParameter("rga", typeof(double));
    
            var tasaImpositivaParameter = tasaImpositiva.HasValue ?
                new ObjectParameter("tasaImpositiva", tasaImpositiva) :
                new ObjectParameter("tasaImpositiva", typeof(double));
    
            var paridadParameter = paridad.HasValue ?
                new ObjectParameter("paridad", paridad) :
                new ObjectParameter("paridad", typeof(double));
    
            var campo_idParameter = campo_id.HasValue ?
                new ObjectParameter("campo_id", campo_id) :
                new ObjectParameter("campo_id", typeof(int));
    
            var equipo_idParameter = equipo_id.HasValue ?
                new ObjectParameter("equipo_id", equipo_id) :
                new ObjectParameter("equipo_id", typeof(int));
    
            var pozo_idParameter = pozo_id.HasValue ?
                new ObjectParameter("pozo_id", pozo_id) :
                new ObjectParameter("pozo_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_calcularOpex", gas_aceiteParameter, rgaParameter, tasaImpositivaParameter, paridadParameter, campo_idParameter, equipo_idParameter, pozo_idParameter);
        }
    }
}
