//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionPozosPemex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Precio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Precio()
        {
            this.Resultadoes = new HashSet<Resultado>();
        }

        public int PrecioId { get; set; }
        [DisplayName("Precio del Crudo")]
        [Range(0, 99999), Required(AllowEmptyStrings = false, ErrorMessage = "El campo Precio del Crudo es requerido.")]
        public double PrecioCrudo { get; set; }
        [DisplayName("Precio del Gas")]
        [Range(0, 99999), Required(AllowEmptyStrings = false, ErrorMessage = "El campo Precio del Crudo es requerido.")]
        public double PrecioGas { get; set; }
        [DisplayName("Año")]
        [Range(0, 99999), Required(AllowEmptyStrings = false, ErrorMessage = "El campo Precio del Crudo es requerido.")]
        public int Ano { get; set; }
        [Required]
        public int CampoId { get; set; }

        public virtual Campo Campo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultado> Resultadoes { get; set; }
    }
}
