//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionPozosPemex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado
    {
        public int ResultadoId { get; set; }
        public int Produccion { get; set; }
        public double IngresoTotalDolares { get; set; }
        public double IngresoTotalPesos { get; set; }
        public double Vpn { get; set; }
        public double VpnDi { get; set; }
        public int CampoId { get; set; }
        public int PozoId { get; set; }
        public int OperacionId { get; set; }
        public int PrecioId { get; set; }
    
        public virtual Campo Campo { get; set; }
        public virtual Operacion Operacion { get; set; }
        public virtual Pozo Pozo { get; set; }
        public virtual Precio Precio { get; set; }
    }
}
